/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    languages: Language;
    sites: Site;
    layouts: Layout;
    pages: Page;
    blocks: Block;
    navigation: Navigation;
    themes: Theme;
    permissions: Permission;
    roles: Role;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    languages: LanguagesSelect<false> | LanguagesSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    layouts: LayoutsSelect<false> | LayoutsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    blocks: BlocksSelect<false> | BlocksSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    themes: ThemesSelect<false> | ThemesSelect<true>;
    permissions: PermissionsSelect<false> | PermissionsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'th') | ('en' | 'th')[];
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: 'en' | 'th';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Roles assigned to this user
   */
  roles: (string | Role)[];
  status?: ('active' | 'inactive' | 'suspended') | null;
  firstName?: string | null;
  lastName?: string | null;
  avatar?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: string;
  /**
   * Role display name (e.g., Administrator, Editor, Author)
   */
  name: string;
  /**
   * Role identifier (e.g., admin, editor, author)
   */
  slug: string;
  /**
   * Description of this role
   */
  description?: string | null;
  /**
   * Role level (1-10, higher number = more permissions)
   */
  level: number;
  /**
   * Parent role for role inheritance (optional)
   */
  parentRole?: (string | null) | Role;
  /**
   * Permissions assigned to this role
   */
  permissions?: (string | Permission)[] | null;
  /**
   * Permissions inherited from parent role (auto-calculated)
   */
  inheritedPermissions?: (string | Permission)[] | null;
  status?: ('active' | 'inactive') | null;
  /**
   * System roles cannot be deleted
   */
  isSystemRole?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions".
 */
export interface Permission {
  id: string;
  /**
   * Permission display name (e.g., Create Pages, Update Sites)
   */
  name: string;
  /**
   * Permission identifier (e.g., pages.create, sites.update)
   */
  slug: string;
  /**
   * Resource this permission applies to
   */
  resource:
    | 'pages'
    | 'sites'
    | 'layouts'
    | 'components'
    | 'languages'
    | 'users'
    | 'roles'
    | 'permissions'
    | 'media'
    | 'all';
  /**
   * Action this permission allows
   */
  action: 'create' | 'read' | 'update' | 'delete' | 'admin' | 'all';
  /**
   * Description of what this permission allows
   */
  description?: string | null;
  status?: ('active' | 'inactive') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages".
 */
export interface Language {
  id: string;
  /**
   * ISO 639-1 language code (e.g., en, th, zh)
   */
  code: string;
  /**
   * Language name in English (e.g., English, Thai)
   */
  name: string;
  /**
   * Native language name (e.g., English, ไทย)
   */
  nativeName?: string | null;
  /**
   * ISO 3166-1 alpha-2 country code (e.g., US, TH)
   */
  countryCode?: string | null;
  /**
   * Flag emoji or icon identifier
   */
  flag?: string | null;
  /**
   * Right-to-left language (e.g., Arabic, Hebrew)
   */
  rtl?: boolean | null;
  /**
   * Date format (e.g., MM/DD/YYYY, DD/MM/YYYY)
   */
  dateFormat?: string | null;
  numberFormat?: {
    /**
     * Locale code for number formatting (e.g., en-US, th-TH)
     */
    code?: string | null;
    /**
     * Currency code (e.g., USD, THB)
     */
    currency?: string | null;
  };
  status?: ('active' | 'inactive') | null;
  /**
   * Display order for language selector
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: string;
  name: string;
  /**
   * Main domain (e.g., example.com)
   */
  domain: string;
  /**
   * Supported subdomains (e.g., blog.example.com)
   */
  subdomains?:
    | {
        subdomain?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Default layout for this site
   */
  defaultLayout?: (string | null) | Layout;
  logo?: (string | null) | Media;
  favicon?: (string | null) | Media;
  seo?: {
    /**
     * Default SEO title
     */
    defaultTitle?: string | null;
    /**
     * Default SEO description
     */
    defaultDescription?: string | null;
    defaultImage?: (string | null) | Media;
  };
  i18n?: {
    /**
     * Enable i18n for this site
     */
    enabled?: boolean | null;
    /**
     * Default language for this site
     */
    defaultLanguage?: (string | null) | Language;
    /**
     * Supported languages for this site
     */
    supportedLanguages?: (string | Language)[] | null;
    /**
     * Language detection method
     */
    languageDetection?: ('path' | 'header' | 'cookie') | null;
    /**
     * Use language prefix in URL (e.g., /en/, /th/)
     */
    pathPrefix?: boolean | null;
    /**
     * Fallback language if translation missing
     */
    fallbackLanguage?: (string | null) | Language;
  };
  /**
   * Select theme configuration for this site
   */
  theme: string | Theme;
  /**
   * Override specific theme values for this site (optional)
   */
  themeOverrides?: {
    /**
     * Border radius base value (rem)
     */
    radius?: number | null;
    colors?: {
      /**
       * Background color (oklch format)
       */
      background?: string | null;
      /**
       * Text color (oklch format)
       */
      foreground?: string | null;
      /**
       * Card background (oklch format)
       */
      card?: string | null;
      /**
       * Card text (oklch format)
       */
      cardForeground?: string | null;
      /**
       * Popover background (oklch format)
       */
      popover?: string | null;
      /**
       * Popover text (oklch format)
       */
      popoverForeground?: string | null;
      /**
       * Primary color (oklch format)
       */
      primary?: string | null;
      /**
       * Primary text (oklch format)
       */
      primaryForeground?: string | null;
      /**
       * Secondary color (oklch format)
       */
      secondary?: string | null;
      /**
       * Secondary text (oklch format)
       */
      secondaryForeground?: string | null;
      /**
       * Muted background (oklch format)
       */
      muted?: string | null;
      /**
       * Muted text (oklch format)
       */
      mutedForeground?: string | null;
      /**
       * Accent color (oklch format)
       */
      accent?: string | null;
      /**
       * Accent text (oklch format)
       */
      accentForeground?: string | null;
      /**
       * Destructive color (oklch format)
       */
      destructive?: string | null;
      /**
       * Border color (oklch format)
       */
      border?: string | null;
      /**
       * Input border color (oklch format)
       */
      input?: string | null;
      /**
       * Focus ring color (oklch format)
       */
      ring?: string | null;
      /**
       * Chart color 1 (oklch format)
       */
      chart1?: string | null;
      /**
       * Chart color 2 (oklch format)
       */
      chart2?: string | null;
      /**
       * Chart color 3 (oklch format)
       */
      chart3?: string | null;
      /**
       * Chart color 4 (oklch format)
       */
      chart4?: string | null;
      /**
       * Chart color 5 (oklch format)
       */
      chart5?: string | null;
      /**
       * Sidebar background (oklch format)
       */
      sidebar?: string | null;
      /**
       * Sidebar text (oklch format)
       */
      sidebarForeground?: string | null;
      /**
       * Sidebar primary (oklch format)
       */
      sidebarPrimary?: string | null;
      /**
       * Sidebar primary text (oklch format)
       */
      sidebarPrimaryForeground?: string | null;
      /**
       * Sidebar accent (oklch format)
       */
      sidebarAccent?: string | null;
      /**
       * Sidebar accent text (oklch format)
       */
      sidebarAccentForeground?: string | null;
      /**
       * Sidebar border (oklch format)
       */
      sidebarBorder?: string | null;
      /**
       * Sidebar ring (oklch format)
       */
      sidebarRing?: string | null;
    };
    darkMode?: {
      background?: string | null;
      foreground?: string | null;
      card?: string | null;
      cardForeground?: string | null;
      popover?: string | null;
      popoverForeground?: string | null;
      primary?: string | null;
      primaryForeground?: string | null;
      secondary?: string | null;
      secondaryForeground?: string | null;
      muted?: string | null;
      mutedForeground?: string | null;
      accent?: string | null;
      accentForeground?: string | null;
      destructive?: string | null;
      border?: string | null;
      input?: string | null;
      ring?: string | null;
      chart1?: string | null;
      chart2?: string | null;
      chart3?: string | null;
      chart4?: string | null;
      chart5?: string | null;
      sidebar?: string | null;
      sidebarForeground?: string | null;
      sidebarPrimary?: string | null;
      sidebarPrimaryForeground?: string | null;
      sidebarAccent?: string | null;
      sidebarAccentForeground?: string | null;
      sidebarBorder?: string | null;
      sidebarRing?: string | null;
    };
    /**
     * Custom Tailwind config overrides
     */
    tailwindConfig?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Generated CSS variables (auto-generated)
     */
    cssVariables?: string | null;
    /**
     * Theme preview screenshot
     */
    themePreview?: (string | null) | Media;
  };
  status?: ('active' | 'inactive') | null;
  createdBy?: (string | null) | User;
  /**
   * Navigation block (should contain a navigation block with menu items)
   */
  navigation?: (string | null) | Block;
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Layout templates composed of block references
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layouts".
 */
export interface Layout {
  id: string;
  name: string;
  /**
   * URL-friendly identifier (e.g., main-layout, simple-layout)
   */
  slug: string;
  description?: string | null;
  /**
   * Layout type based on next-ts patterns
   */
  type: 'main' | 'simple' | 'auth' | 'blank';
  /**
   * Layout components - Use Block References for reusable components
   */
  components?:
    | {
        /**
         * Reference a reusable block (e.g., Header, Footer, Sidebar)
         */
        block: string | Block;
        /**
         * Props to pass to the block (JSON object). Example: { "variant": "dark", "sticky": true }
         */
        props?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Enable/disable this component
         */
        enabled?: boolean | null;
        /**
         * Where this component should be rendered in the layout
         */
        position: 'before' | 'content' | 'after' | 'header' | 'navigation' | 'footer' | 'sidebar';
        id?: string | null;
        blockName?: string | null;
        blockType: 'blockRef';
      }[]
    | null;
  /**
   * Layout-specific theme overrides (optional)
   */
  themeOverrides?: {
    /**
     * Override specific colors for this layout
     */
    colors?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Override spacing values
     */
    spacing?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Preview image for this layout
   */
  preview?: (string | null) | Media;
  status?: ('draft' | 'published') | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable content blocks that can be referenced by pages and layouts
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocks".
 */
export interface Block {
  id: string;
  /**
   * Block name (e.g., "Hero - Landing", "Main Navigation")
   */
  name: string;
  /**
   * Unique identifier for referencing (e.g., "hero-landing", "main-nav")
   */
  slug: string;
  /**
   * What this block is for and when to use it
   */
  description?: string | null;
  /**
   * Global = site-wide, Shared = reusable, Template = parameterized
   */
  type: 'global' | 'shared' | 'template';
  /**
   * Category for organization
   */
  category?:
    | ('header' | 'hero' | 'content' | 'features' | 'pricing' | 'testimonials' | 'cta' | 'footer' | 'other')
    | null;
  /**
   * Blocks that compose this content
   */
  blocks: (
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        text: string;
        level?: ('h1' | 'h2' | 'h3' | 'h4') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heading';
      }
    | {
        /**
         * Slot identifier (e.g., "actions", "content")
         */
        name: string;
        /**
         * Human-readable label
         */
        label?: string | null;
        /**
         * What should be placed in this slot
         */
        description?: string | null;
        required?: boolean | null;
        /**
         * Default content if slot is not filled
         */
        defaultBlocks?:
          | {
              content?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'richText';
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'slot';
      }
    | {
        columns?: ('1' | '2' | '3' | '4') | null;
        gap?: ('sm' | 'md' | 'lg') | null;
        items?:
          | {
              content?:
                | {
                    content?: {
                      root: {
                        type: string;
                        children: {
                          type: any;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    } | null;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'richText';
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'grid';
      }
    | {
        /**
         * Unique key to store fetched data in context
         */
        dataKey: string;
        /**
         * Multiple data sources to fetch from
         */
        sources: {
          type: 'collection' | 'global' | 'endpoint';
          collection?:
            | (
                | 'blocks'
                | 'pages'
                | 'layouts'
                | 'users'
                | 'media'
                | 'roles'
                | 'permissions'
                | 'themes'
                | 'sites'
                | 'languages'
              )
            | null;
          global?: 'settings' | null;
          /**
           * API endpoint URL
           */
          endpoint?: string | null;
          /**
           * Optional key to store this source data separately. If not provided, data will be merged with other sources.
           */
          dataKey?: string | null;
          query?: {
            /**
             * Limit for this source (overrides global limit if set)
             */
            limit?: number | null;
            /**
             * Sort field for this source (e.g., "-createdAt")
             */
            sort?: string | null;
            /**
             * Query conditions for this source (JSON format)
             */
            where?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
          };
          id?: string | null;
        }[];
        /**
         * How to merge data from multiple sources. "union" combines all results, "separate" stores each source under its dataKey
         */
        mergeStrategy?: ('union' | 'separate') | null;
        query?: {
          limit?: number | null;
          /**
           * Sort field (e.g., "-createdAt")
           */
          sort?: string | null;
        };
        transform?: {
          type?: ('none' | 'count' | 'sum' | 'average') | null;
        };
        /**
         * Fetch count statistics for tabs (separate from main data query)
         */
        fetchStats?: boolean | null;
        /**
         * Configuration for statistics fetching
         */
        statsConfig?: {
          /**
           * Collection to fetch stats from (defaults to first source collection)
           */
          statsCollection?:
            | (
                | ''
                | 'blocks'
                | 'pages'
                | 'layouts'
                | 'users'
                | 'media'
                | 'roles'
                | 'permissions'
                | 'themes'
                | 'sites'
                | 'languages'
              )
            | null;
          /**
           * Field to group by for counting (e.g., "status", "pageStatus", "type")
           */
          groupBy: string;
          /**
           * Key to store stats data in context
           */
          statsDataKey?: string | null;
          /**
           * Specific values to count (leave empty to count all unique values automatically)
           */
          includeValues?:
            | {
                value: string;
                id?: string | null;
              }[]
            | null;
          /**
           * Automatically generate tabs from stats data (if disabled, only show tabs from statusTabsConfig)
           */
          autoGenerateTabs?: boolean | null;
        };
        children?:
          | (
              | {
                  /**
                   * Use data from parent DataFetch
                   */
                  useExternalData?: boolean | null;
                  /**
                   * Data key from parent DataFetch
                   */
                  dataKey?: string | null;
                  title?: string | null;
                  collection:
                    | 'blocks'
                    | 'pages'
                    | 'layouts'
                    | 'users'
                    | 'media'
                    | 'roles'
                    | 'permissions'
                    | 'themes'
                    | 'sites'
                    | 'languages';
                  /**
                   * Table columns configuration
                   */
                  columns?:
                    | {
                        /**
                         * Unique column identifier
                         */
                        key: string;
                        /**
                         * Column header label
                         */
                        label: string;
                        /**
                         * Custom accessor (template: "{firstName} {lastName}", path: "user.email", or field: "email"). If not provided, uses key.
                         */
                        accessor?: string | null;
                        /**
                         * Enable sorting for this column
                         */
                        sortable?: boolean | null;
                        /**
                         * Column display type
                         */
                        type?: ('text' | 'number' | 'date' | 'boolean' | 'badge' | 'custom') | null;
                        /**
                         * Column width (e.g., "200px", "20%")
                         */
                        width?: string | null;
                        /**
                         * Custom rendering blocks for this column. Use for complex cell content like avatars, badges, links, etc.
                         */
                        blocks?:
                          | (
                              | {
                                  /**
                                   * Field name to display
                                   */
                                  field: string;
                                  variant?: ('default' | 'success' | 'warning' | 'error' | 'info') | null;
                                  /**
                                   * Map field values to badge variants. Example: {"active": "success", "inactive": "error"}
                                   */
                                  colorMap?:
                                    | {
                                        [k: string]: unknown;
                                      }
                                    | unknown[]
                                    | string
                                    | number
                                    | boolean
                                    | null;
                                  id?: string | null;
                                  blockName?: string | null;
                                  blockType: 'badge';
                                }
                              | {
                                  /**
                                   * Field containing image URL
                                   */
                                  imageField?: string | null;
                                  /**
                                   * Field for fallback initials
                                   */
                                  nameField?: string | null;
                                  size?: ('sm' | 'md' | 'lg') | null;
                                  id?: string | null;
                                  blockName?: string | null;
                                  blockType: 'avatar';
                                }
                              | {
                                  /**
                                   * Field for link text
                                   */
                                  textField: string;
                                  /**
                                   * Field for URL (optional)
                                   */
                                  urlField?: string | null;
                                  /**
                                   * URL pattern template. Example: "/users/{id}"
                                   */
                                  urlPattern?: string | null;
                                  /**
                                   * Open in new tab
                                   */
                                  external?: boolean | null;
                                  id?: string | null;
                                  blockName?: string | null;
                                  blockType: 'link';
                                }
                              | {
                                  /**
                                   * Field containing icon name
                                   */
                                  iconField?: string | null;
                                  /**
                                   * Map field values to icon names. Example: {"user": "UserIcon", "admin": "ShieldIcon"}
                                   */
                                  iconMap?:
                                    | {
                                        [k: string]: unknown;
                                      }
                                    | unknown[]
                                    | string
                                    | number
                                    | boolean
                                    | null;
                                  /**
                                   * Field for text next to icon
                                   */
                                  textField?: string | null;
                                  id?: string | null;
                                  blockName?: string | null;
                                  blockType: 'icon';
                                }
                              | {
                                  /**
                                   * Field name to display
                                   */
                                  field: string;
                                  /**
                                   * Template string. Example: "{firstName} {lastName}"
                                   */
                                  template?: string | null;
                                  /**
                                   * CSS classes for styling
                                   */
                                  className?: string | null;
                                  /**
                                   * Max characters before truncating
                                   */
                                  truncate?: number | null;
                                  id?: string | null;
                                  blockName?: string | null;
                                  blockType: 'text';
                                }
                              | {
                                  /**
                                   * Field containing image URL
                                   */
                                  urlField: string;
                                  /**
                                   * Field for alt text
                                   */
                                  altField?: string | null;
                                  width?: number | null;
                                  height?: number | null;
                                  rounded?: boolean | null;
                                  id?: string | null;
                                  blockName?: string | null;
                                  blockType: 'image';
                                }
                              | {
                                  direction?: ('horizontal' | 'vertical') | null;
                                  gap?: ('none' | 'sm' | 'md' | 'lg') | null;
                                  items?:
                                    | {
                                        type: 'text' | 'badge' | 'avatar' | 'icon';
                                        field?: string | null;
                                        /**
                                         * Configuration for the item
                                         */
                                        config?:
                                          | {
                                              [k: string]: unknown;
                                            }
                                          | unknown[]
                                          | string
                                          | number
                                          | boolean
                                          | null;
                                        id?: string | null;
                                      }[]
                                    | null;
                                  id?: string | null;
                                  blockName?: string | null;
                                  blockType: 'group';
                                }
                            )[]
                          | null;
                        id?: string | null;
                      }[]
                    | null;
                  searchFields?:
                    | {
                        field: string;
                        id?: string | null;
                      }[]
                    | null;
                  /**
                   * Show filter tabs with count statistics
                   */
                  showStatusTabs?: boolean | null;
                  /**
                   * Use stats from parent DataFetch block (requires fetchStats enabled in parent)
                   */
                  useParentStats?: boolean | null;
                  /**
                   * Field name to count and filter by
                   */
                  statusTabsField?: string | null;
                  /**
                   * Define tabs with their values, labels, and styling
                   */
                  statusTabsConfig?:
                    | {
                        /**
                         * Value to filter by (e.g., "draft", "published", "active")
                         */
                        value: string;
                        /**
                         * Display label for the tab
                         */
                        label: string;
                        /**
                         * Badge color variant
                         */
                        variant?: ('default' | 'success' | 'warning' | 'error' | 'info' | 'secondary') | null;
                        /**
                         * Optional icon name from lucide-react (e.g., "Check", "Clock", "XCircle")
                         */
                        icon?: string | null;
                        /**
                         * Optional description for this tab
                         */
                        description?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  /**
                   * Label for the "All" tab
                   */
                  allTabLabel?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'blocksTable';
                }
              | {
                  title: string;
                  dataKey?: string | null;
                  icon?: string | null;
                  format?: ('number' | 'currency' | 'percentage') | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'statCard';
                }
            )[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'dataFetch';
      }
    | {
        /**
         * Table title (optional)
         */
        title?: string | null;
        /**
         * Table description (optional)
         */
        description?: string | null;
        /**
         * Collection to fetch data from
         */
        collection:
          | 'blocks'
          | 'pages'
          | 'layouts'
          | 'users'
          | 'media'
          | 'roles'
          | 'permissions'
          | 'themes'
          | 'sites'
          | 'languages';
        /**
         * Column configuration (JSON array). Leave empty for auto-detection. Example: [{"key":"name","label":"Name"},{"key":"status","label":"Status"}]
         */
        columns?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Items per page
         */
        limit?: number | null;
        /**
         * Fields to search in
         */
        searchFields?:
          | {
              field: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Filter configuration (JSON array). Example: [{"field":"status","label":"Status","type":"select","options":[{"label":"Draft","value":"draft"}]}]
         */
        filterFields?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Relationship population settings
         */
        populate?: {
          /**
           * Population depth (0 = no population)
           */
          depth?: number | null;
          /**
           * Fields to populate
           */
          fields?:
            | {
                field?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        /**
         * Fields to select (comma-separated)
         */
        select?: string | null;
        defaultSort?: {
          /**
           * Field to sort by
           */
          field?: string | null;
          order?: ('asc' | 'desc') | null;
        };
        /**
         * Show filter tabs with count statistics
         */
        showStatusTabs?: boolean | null;
        /**
         * Use stats from parent DataFetch block (requires fetchStats enabled in parent)
         */
        useParentStats?: boolean | null;
        /**
         * Field name to count and filter by
         */
        statusTabsField?: string | null;
        /**
         * Define tabs with their values, labels, and styling
         */
        statusTabsConfig?:
          | {
              /**
               * Value to filter by (e.g., "draft", "published", "active")
               */
              value: string;
              /**
               * Display label for the tab
               */
              label: string;
              /**
               * Badge color variant
               */
              variant?: ('default' | 'success' | 'warning' | 'error' | 'info' | 'secondary') | null;
              /**
               * Optional icon name from lucide-react (e.g., "Check", "Clock", "XCircle")
               */
              icon?: string | null;
              /**
               * Optional description for this tab
               */
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Label for the "All" tab
         */
        allTabLabel?: string | null;
        /**
         * Show action buttons (view, edit, delete)
         */
        showActions?: boolean | null;
        /**
         * Default actions configuration (JSON object). Set to false to disable. Example: {"view":true,"edit":true,"delete":true,"copy":false}
         */
        defaultActions?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Sync table state to URL parameters
         */
        syncUrl?: boolean | null;
        /**
         * Group/namespace for URL params (for multiple tables on same page)
         */
        urlGroup?: string | null;
        /**
         * Use data from DataFetch context instead of fetching internally
         */
        useExternalData?: boolean | null;
        /**
         * Data key from DataFetch context (required if useExternalData is true)
         */
        dataKey?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'table';
      }
    | {
        /**
         * Unique ID for this navigation instance (e.g., "main-nav", "sidebar-nav")
         */
        navigationId?: string | null;
        /**
         * Navigation title (e.g., "Main Navigation", "Sidebar Menu")
         */
        title?: string | null;
        /**
         * Navigation menu items (supports up to 2 levels of nesting)
         */
        items?:
          | {
              /**
               * Menu item title
               */
              title: string;
              /**
               * Link path (e.g., "/dashboard", "/users")
               */
              path?: string | null;
              /**
               * Lucide icon name (e.g., "Home", "Users", "Settings", "ChevronRight")
               */
              icon?: string | null;
              /**
               * Optional caption/badge text (e.g., "New", "Beta")
               */
              caption?: string | null;
              /**
               * Disable this menu item
               */
              disabled?: boolean | null;
              /**
               * Open link in new tab (for external links)
               */
              external?: boolean | null;
              /**
               * Group label (for visual separation, e.g., "General", "Pages", "Other")
               */
              groupLabel?: string | null;
              /**
               * Sub-menu items (Level 2) - Up to 3 levels total
               */
              children?:
                | {
                    title: string;
                    path?: string | null;
                    icon?: string | null;
                    caption?: string | null;
                    disabled?: boolean | null;
                    external?: boolean | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'navigation';
      }
    | {
        /**
         * Unique form identifier (e.g., "contact-form", "user-registration")
         */
        formId: string;
        /**
         * Form title (shown in dialog/page header)
         */
        title: string;
        /**
         * Form description (shown below title)
         */
        description?: string | null;
        /**
         * How the form should be displayed
         */
        viewType: 'dialog' | 'page' | 'sidebar-left' | 'sidebar-right';
        /**
         * Dialog/Page size
         */
        viewSize?: ('sm' | 'md' | 'lg' | 'xl' | 'full') | null;
        /**
         * Sidebar display mode
         */
        viewMode?: ('overlay' | 'push') | null;
        /**
         * Button text to open the form
         */
        triggerLabel: string;
        /**
         * Button style
         */
        triggerVariant?: ('default' | 'primary' | 'secondary' | 'outline' | 'ghost' | 'link' | 'destructive') | null;
        /**
         * Button size
         */
        triggerSize?: ('sm' | 'default' | 'lg') | null;
        /**
         * Form fields configuration
         */
        fields: {
          /**
           * Field name (used as form data key)
           */
          name: string;
          /**
           * Field label (shown to user)
           */
          label: string;
          /**
           * Field input type
           */
          type: 'text' | 'email' | 'password' | 'number' | 'textarea' | 'select' | 'checkbox' | 'date' | 'file';
          /**
           * Placeholder text
           */
          placeholder?: string | null;
          /**
           * Is this field required?
           */
          required?: boolean | null;
          /**
           * Minimum length (for text fields)
           */
          minLength?: number | null;
          /**
           * Maximum length (for text fields)
           */
          maxLength?: number | null;
          /**
           * Minimum value (for number fields)
           */
          min?: number | null;
          /**
           * Maximum value (for number fields)
           */
          max?: number | null;
          /**
           * Regex pattern for validation
           */
          pattern?: string | null;
          /**
           * Options for select field
           */
          options?:
            | {
                label: string;
                value: string;
                id?: string | null;
              }[]
            | null;
          /**
           * Default value
           */
          defaultValue?: string | null;
          /**
           * Helper text shown below field
           */
          helperText?: string | null;
          id?: string | null;
        }[];
        /**
         * API endpoint to submit form data (e.g., "/api/contact")
         */
        submitEndpoint: string;
        /**
         * HTTP method for submission
         */
        submitMethod?: ('POST' | 'PUT' | 'PATCH') | null;
        /**
         * Submit button label
         */
        submitLabel?: string | null;
        /**
         * Cancel button label
         */
        cancelLabel?: string | null;
        /**
         * Success toast message
         */
        successMessage?: string | null;
        /**
         * Error toast message
         */
        errorMessage?: string | null;
        /**
         * Redirect to this URL after successful submission (optional)
         */
        redirectUrl?: string | null;
        /**
         * Show step indicator for multi-step forms
         */
        showProgressIndicator?: boolean | null;
        /**
         * Auto-save form data to localStorage
         */
        enableAutosave?: boolean | null;
        /**
         * Custom CSS classes (space-separated)
         */
        customCss?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'form';
      }
  )[];
  /**
   * Define injection points where pages can insert custom content
   */
  slots?:
    | {
        /**
         * Slot name (must match slot block above)
         */
        name: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Define props that can be passed when using this block
   */
  propsSchema?:
    | {
        /**
         * Prop key (e.g., "title", "theme")
         */
        key: string;
        type: 'text' | 'number' | 'boolean' | 'select' | 'json';
        /**
         * Human-readable label
         */
        label?: string | null;
        description?: string | null;
        required?: boolean | null;
        /**
         * Default value if not provided
         */
        defaultValue?: string | null;
        /**
         * Options for select type (array of {label, value})
         */
        options?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  status?: ('draft' | 'published' | 'archived') | null;
  /**
   * Tags for organization and search
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Version number (e.g., "1.0.0")
   */
  version?: string | null;
  /**
   * Preview screenshot for visual selection
   */
  preview?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Theme configurations for sites
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes".
 */
export interface Theme {
  id: string;
  /**
   * Theme name (e.g., "Dark Professional", "Light Minimal")
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., "dark-professional")
   */
  slug: string;
  /**
   * Brief description of this theme
   */
  description?: string | null;
  /**
   * Default color mode for this theme
   */
  mode: 'light' | 'dark' | 'auto';
  /**
   * Primary brand color (hex, rgb, or hsl)
   */
  primaryColor: string;
  /**
   * Text color on primary background
   */
  primaryForeground?: string | null;
  secondaryColor?: string | null;
  secondaryForeground?: string | null;
  /**
   * Main background color
   */
  backgroundColor?: string | null;
  /**
   * Main text color
   */
  foregroundColor?: string | null;
  /**
   * Muted background color
   */
  mutedColor?: string | null;
  mutedForeground?: string | null;
  borderColor?: string | null;
  inputColor?: string | null;
  /**
   * Focus ring color
   */
  ringColor?: string | null;
  successColor?: string | null;
  warningColor?: string | null;
  errorColor?: string | null;
  infoColor?: string | null;
  fontFamily?: {
    /**
     * Sans-serif font stack
     */
    sans?: string | null;
    serif?: string | null;
    mono?: string | null;
  };
  fontSize?: {
    /**
     * Base font size
     */
    base?: string | null;
    /**
     * Type scale ratio
     */
    scale?: ('1.2' | '1.25' | '1.333' | '1.618') | null;
  };
  spacing?: {
    /**
     * Base spacing unit
     */
    unit?: ('4' | '8' | '16') | null;
    containerMaxWidth?: string | null;
    contentMaxWidth?: string | null;
  };
  borderRadius?: {
    sm?: string | null;
    md?: string | null;
    lg?: string | null;
  };
  shadow?: {
    sm?: string | null;
    md?: string | null;
    lg?: string | null;
  };
  /**
   * Additional custom CSS variables
   */
  customCSS?: string | null;
  status: 'active' | 'inactive';
  /**
   * Set as default theme for new sites
   */
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pages composed of blocks and minimal local content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * Page title
   */
  title: string;
  /**
   * URL path (e.g., about, contact-us)
   */
  slug: string;
  /**
   * Parent page for hierarchical structure
   */
  parentPage?: (string | null) | Page;
  /**
   * Page author
   */
  author?: (string | null) | User;
  /**
   * Page status (separate from draft _status)
   */
  pageStatus?: ('draft' | 'published' | 'archived') | null;
  /**
   * Page content - Use Block References for complex content
   */
  content?:
    | (
        | {
            /**
             * Reference a reusable block
             */
            block: string | Block;
            /**
             * Props to pass to the block (JSON object). Example: { "title": "Welcome", "theme": "dark" }
             */
            props?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            /**
             * Fill block slots with custom content
             */
            slots?:
              | {
                  /**
                   * Name of the slot to fill
                   */
                  slotName: string;
                  /**
                   * Content to inject into the slot
                   */
                  content?:
                    | (
                        | {
                            content: {
                              root: {
                                type: string;
                                children: {
                                  type: any;
                                  version: number;
                                  [k: string]: unknown;
                                }[];
                                direction: ('ltr' | 'rtl') | null;
                                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                indent: number;
                                version: number;
                              };
                              [k: string]: unknown;
                            };
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'richText';
                          }
                        | {
                            text: string;
                            level?: ('h1' | 'h2' | 'h3' | 'h4') | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'heading';
                          }
                      )[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Override block settings
             */
            overrides?: {
              /**
               * Additional CSS classes
               */
              cssClass?: string | null;
              backgroundColor?: ('default' | 'primary' | 'secondary' | 'muted') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'blockRef';
          }
        | {
            /**
             * Rich text content
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            maxWidth?: ('prose' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            text: string;
            level: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
            align?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            columns: '1' | '2' | '3' | '4';
            gap?: ('sm' | 'md' | 'lg') | null;
            items: {
              content?:
                | (
                    | {
                        content: {
                          root: {
                            type: string;
                            children: {
                              type: any;
                              version: number;
                              [k: string]: unknown;
                            }[];
                            direction: ('ltr' | 'rtl') | null;
                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                            indent: number;
                            version: number;
                          };
                          [k: string]: unknown;
                        };
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'richText';
                      }
                    | {
                        text: string;
                        level?: ('h2' | 'h3' | 'h4') | null;
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'heading';
                      }
                  )[]
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'grid';
          }
        | {
            image: string | Media;
            /**
             * Alternative text for accessibility
             */
            alt?: string | null;
            caption?: string | null;
            size?: ('small' | 'medium' | 'large' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            height: 'sm' | 'md' | 'lg' | 'xl';
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer';
          }
        | {
            style?: ('solid' | 'dashed' | 'dotted') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'divider';
          }
      )[]
    | null;
  /**
   * SEO and meta information
   */
  seo?: {
    /**
     * Meta title (leave empty to use page title)
     */
    metaTitle?: string | null;
    /**
     * Meta description for search engines
     */
    metaDescription?: string | null;
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Open Graph image for social sharing
     */
    ogImage?: (string | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Order for navigation menus
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage navigation menus and menu items
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  /**
   * Navigation name (e.g., "Main Navigation", "Footer Menu")
   */
  name: string;
  /**
   * Unique identifier (e.g., "main-nav", "footer-menu")
   */
  slug: string;
  /**
   * Optional description for this navigation
   */
  description?: string | null;
  /**
   * Where this navigation should appear
   */
  location: 'main' | 'sidebar' | 'topbar' | 'footer' | 'mobile' | 'dashboard' | 'other';
  /**
   * Navigation menu items (supports 2 levels of nesting)
   */
  items: {
    /**
     * Menu item title
     */
    title: string;
    /**
     * Link path (e.g., "/dashboard", "/users")
     */
    path?: string | null;
    /**
     * Lucide icon name (e.g., "Home", "Users", "Settings")
     */
    icon?: string | null;
    /**
     * Optional caption/badge text (e.g., "New", "Beta")
     */
    caption?: string | null;
    /**
     * Disable this menu item
     */
    disabled?: boolean | null;
    /**
     * Open link in new tab (for external links)
     */
    external?: boolean | null;
    /**
     * Group label for visual separation (e.g., "General", "Settings")
     */
    groupLabel?: string | null;
    /**
     * Display order (lower numbers appear first)
     */
    order?: number | null;
    /**
     * Sub-menu items (Level 2)
     */
    children?:
      | {
          title: string;
          path?: string | null;
          icon?: string | null;
          caption?: string | null;
          disabled?: boolean | null;
          external?: boolean | null;
          order?: number | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  /**
   * Navigation status
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Assign this navigation to a specific site (optional)
   */
  site?: (string | null) | Site;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'languages';
        value: string | Language;
      } | null)
    | ({
        relationTo: 'sites';
        value: string | Site;
      } | null)
    | ({
        relationTo: 'layouts';
        value: string | Layout;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'blocks';
        value: string | Block;
      } | null)
    | ({
        relationTo: 'navigation';
        value: string | Navigation;
      } | null)
    | ({
        relationTo: 'themes';
        value: string | Theme;
      } | null)
    | ({
        relationTo: 'permissions';
        value: string | Permission;
      } | null)
    | ({
        relationTo: 'roles';
        value: string | Role;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  status?: T;
  firstName?: T;
  lastName?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages_select".
 */
export interface LanguagesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  nativeName?: T;
  countryCode?: T;
  flag?: T;
  rtl?: T;
  dateFormat?: T;
  numberFormat?:
    | T
    | {
        code?: T;
        currency?: T;
      };
  status?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  subdomains?:
    | T
    | {
        subdomain?: T;
        id?: T;
      };
  defaultLayout?: T;
  logo?: T;
  favicon?: T;
  seo?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
        defaultImage?: T;
      };
  i18n?:
    | T
    | {
        enabled?: T;
        defaultLanguage?: T;
        supportedLanguages?: T;
        languageDetection?: T;
        pathPrefix?: T;
        fallbackLanguage?: T;
      };
  theme?: T;
  themeOverrides?:
    | T
    | {
        radius?: T;
        colors?:
          | T
          | {
              background?: T;
              foreground?: T;
              card?: T;
              cardForeground?: T;
              popover?: T;
              popoverForeground?: T;
              primary?: T;
              primaryForeground?: T;
              secondary?: T;
              secondaryForeground?: T;
              muted?: T;
              mutedForeground?: T;
              accent?: T;
              accentForeground?: T;
              destructive?: T;
              border?: T;
              input?: T;
              ring?: T;
              chart1?: T;
              chart2?: T;
              chart3?: T;
              chart4?: T;
              chart5?: T;
              sidebar?: T;
              sidebarForeground?: T;
              sidebarPrimary?: T;
              sidebarPrimaryForeground?: T;
              sidebarAccent?: T;
              sidebarAccentForeground?: T;
              sidebarBorder?: T;
              sidebarRing?: T;
            };
        darkMode?:
          | T
          | {
              background?: T;
              foreground?: T;
              card?: T;
              cardForeground?: T;
              popover?: T;
              popoverForeground?: T;
              primary?: T;
              primaryForeground?: T;
              secondary?: T;
              secondaryForeground?: T;
              muted?: T;
              mutedForeground?: T;
              accent?: T;
              accentForeground?: T;
              destructive?: T;
              border?: T;
              input?: T;
              ring?: T;
              chart1?: T;
              chart2?: T;
              chart3?: T;
              chart4?: T;
              chart5?: T;
              sidebar?: T;
              sidebarForeground?: T;
              sidebarPrimary?: T;
              sidebarPrimaryForeground?: T;
              sidebarAccent?: T;
              sidebarAccentForeground?: T;
              sidebarBorder?: T;
              sidebarRing?: T;
            };
        tailwindConfig?: T;
        cssVariables?: T;
        themePreview?: T;
      };
  status?: T;
  createdBy?: T;
  navigation?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layouts_select".
 */
export interface LayoutsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  type?: T;
  components?:
    | T
    | {
        blockRef?:
          | T
          | {
              block?: T;
              props?: T;
              enabled?: T;
              position?: T;
              id?: T;
              blockName?: T;
            };
      };
  themeOverrides?:
    | T
    | {
        colors?: T;
        spacing?: T;
      };
  preview?: T;
  status?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parentPage?: T;
  author?: T;
  pageStatus?: T;
  content?:
    | T
    | {
        blockRef?:
          | T
          | {
              block?: T;
              props?: T;
              slots?:
                | T
                | {
                    slotName?: T;
                    content?:
                      | T
                      | {
                          richText?:
                            | T
                            | {
                                content?: T;
                                id?: T;
                                blockName?: T;
                              };
                          heading?:
                            | T
                            | {
                                text?: T;
                                level?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              overrides?:
                | T
                | {
                    cssClass?: T;
                    backgroundColor?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              maxWidth?: T;
              id?: T;
              blockName?: T;
            };
        heading?:
          | T
          | {
              text?: T;
              level?: T;
              align?: T;
              id?: T;
              blockName?: T;
            };
        grid?:
          | T
          | {
              columns?: T;
              gap?: T;
              items?:
                | T
                | {
                    content?:
                      | T
                      | {
                          richText?:
                            | T
                            | {
                                content?: T;
                                id?: T;
                                blockName?: T;
                              };
                          heading?:
                            | T
                            | {
                                text?: T;
                                level?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              alt?: T;
              caption?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              height?: T;
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              style?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        ogImage?: T;
      };
  publishedAt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocks_select".
 */
export interface BlocksSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  type?: T;
  category?: T;
  blocks?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        heading?:
          | T
          | {
              text?: T;
              level?: T;
              id?: T;
              blockName?: T;
            };
        slot?:
          | T
          | {
              name?: T;
              label?: T;
              description?: T;
              required?: T;
              defaultBlocks?:
                | T
                | {
                    richText?:
                      | T
                      | {
                          content?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        grid?:
          | T
          | {
              columns?: T;
              gap?: T;
              items?:
                | T
                | {
                    content?:
                      | T
                      | {
                          richText?:
                            | T
                            | {
                                content?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        dataFetch?:
          | T
          | {
              dataKey?: T;
              sources?:
                | T
                | {
                    type?: T;
                    collection?: T;
                    global?: T;
                    endpoint?: T;
                    dataKey?: T;
                    query?:
                      | T
                      | {
                          limit?: T;
                          sort?: T;
                          where?: T;
                        };
                    id?: T;
                  };
              mergeStrategy?: T;
              query?:
                | T
                | {
                    limit?: T;
                    sort?: T;
                  };
              transform?:
                | T
                | {
                    type?: T;
                  };
              fetchStats?: T;
              statsConfig?:
                | T
                | {
                    statsCollection?: T;
                    groupBy?: T;
                    statsDataKey?: T;
                    includeValues?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    autoGenerateTabs?: T;
                  };
              children?:
                | T
                | {
                    blocksTable?:
                      | T
                      | {
                          useExternalData?: T;
                          dataKey?: T;
                          title?: T;
                          collection?: T;
                          columns?:
                            | T
                            | {
                                key?: T;
                                label?: T;
                                accessor?: T;
                                sortable?: T;
                                type?: T;
                                width?: T;
                                blocks?:
                                  | T
                                  | {
                                      badge?:
                                        | T
                                        | {
                                            field?: T;
                                            variant?: T;
                                            colorMap?: T;
                                            id?: T;
                                            blockName?: T;
                                          };
                                      avatar?:
                                        | T
                                        | {
                                            imageField?: T;
                                            nameField?: T;
                                            size?: T;
                                            id?: T;
                                            blockName?: T;
                                          };
                                      link?:
                                        | T
                                        | {
                                            textField?: T;
                                            urlField?: T;
                                            urlPattern?: T;
                                            external?: T;
                                            id?: T;
                                            blockName?: T;
                                          };
                                      icon?:
                                        | T
                                        | {
                                            iconField?: T;
                                            iconMap?: T;
                                            textField?: T;
                                            id?: T;
                                            blockName?: T;
                                          };
                                      text?:
                                        | T
                                        | {
                                            field?: T;
                                            template?: T;
                                            className?: T;
                                            truncate?: T;
                                            id?: T;
                                            blockName?: T;
                                          };
                                      image?:
                                        | T
                                        | {
                                            urlField?: T;
                                            altField?: T;
                                            width?: T;
                                            height?: T;
                                            rounded?: T;
                                            id?: T;
                                            blockName?: T;
                                          };
                                      group?:
                                        | T
                                        | {
                                            direction?: T;
                                            gap?: T;
                                            items?:
                                              | T
                                              | {
                                                  type?: T;
                                                  field?: T;
                                                  config?: T;
                                                  id?: T;
                                                };
                                            id?: T;
                                            blockName?: T;
                                          };
                                    };
                                id?: T;
                              };
                          searchFields?:
                            | T
                            | {
                                field?: T;
                                id?: T;
                              };
                          showStatusTabs?: T;
                          useParentStats?: T;
                          statusTabsField?: T;
                          statusTabsConfig?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                variant?: T;
                                icon?: T;
                                description?: T;
                                id?: T;
                              };
                          allTabLabel?: T;
                          id?: T;
                          blockName?: T;
                        };
                    statCard?:
                      | T
                      | {
                          title?: T;
                          dataKey?: T;
                          icon?: T;
                          format?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        table?:
          | T
          | {
              title?: T;
              description?: T;
              collection?: T;
              columns?: T;
              limit?: T;
              searchFields?:
                | T
                | {
                    field?: T;
                    id?: T;
                  };
              filterFields?: T;
              populate?:
                | T
                | {
                    depth?: T;
                    fields?:
                      | T
                      | {
                          field?: T;
                          id?: T;
                        };
                  };
              select?: T;
              defaultSort?:
                | T
                | {
                    field?: T;
                    order?: T;
                  };
              showStatusTabs?: T;
              useParentStats?: T;
              statusTabsField?: T;
              statusTabsConfig?:
                | T
                | {
                    value?: T;
                    label?: T;
                    variant?: T;
                    icon?: T;
                    description?: T;
                    id?: T;
                  };
              allTabLabel?: T;
              showActions?: T;
              defaultActions?: T;
              syncUrl?: T;
              urlGroup?: T;
              useExternalData?: T;
              dataKey?: T;
              id?: T;
              blockName?: T;
            };
        navigation?:
          | T
          | {
              navigationId?: T;
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    path?: T;
                    icon?: T;
                    caption?: T;
                    disabled?: T;
                    external?: T;
                    groupLabel?: T;
                    children?:
                      | T
                      | {
                          title?: T;
                          path?: T;
                          icon?: T;
                          caption?: T;
                          disabled?: T;
                          external?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        form?:
          | T
          | {
              formId?: T;
              title?: T;
              description?: T;
              viewType?: T;
              viewSize?: T;
              viewMode?: T;
              triggerLabel?: T;
              triggerVariant?: T;
              triggerSize?: T;
              fields?:
                | T
                | {
                    name?: T;
                    label?: T;
                    type?: T;
                    placeholder?: T;
                    required?: T;
                    minLength?: T;
                    maxLength?: T;
                    min?: T;
                    max?: T;
                    pattern?: T;
                    options?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                    defaultValue?: T;
                    helperText?: T;
                    id?: T;
                  };
              submitEndpoint?: T;
              submitMethod?: T;
              submitLabel?: T;
              cancelLabel?: T;
              successMessage?: T;
              errorMessage?: T;
              redirectUrl?: T;
              showProgressIndicator?: T;
              enableAutosave?: T;
              customCss?: T;
              id?: T;
              blockName?: T;
            };
      };
  slots?:
    | T
    | {
        name?: T;
        description?: T;
        id?: T;
      };
  propsSchema?:
    | T
    | {
        key?: T;
        type?: T;
        label?: T;
        description?: T;
        required?: T;
        defaultValue?: T;
        options?: T;
        id?: T;
      };
  status?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  version?: T;
  preview?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  location?: T;
  items?:
    | T
    | {
        title?: T;
        path?: T;
        icon?: T;
        caption?: T;
        disabled?: T;
        external?: T;
        groupLabel?: T;
        order?: T;
        children?:
          | T
          | {
              title?: T;
              path?: T;
              icon?: T;
              caption?: T;
              disabled?: T;
              external?: T;
              order?: T;
              id?: T;
            };
        id?: T;
      };
  status?: T;
  site?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes_select".
 */
export interface ThemesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  mode?: T;
  primaryColor?: T;
  primaryForeground?: T;
  secondaryColor?: T;
  secondaryForeground?: T;
  backgroundColor?: T;
  foregroundColor?: T;
  mutedColor?: T;
  mutedForeground?: T;
  borderColor?: T;
  inputColor?: T;
  ringColor?: T;
  successColor?: T;
  warningColor?: T;
  errorColor?: T;
  infoColor?: T;
  fontFamily?:
    | T
    | {
        sans?: T;
        serif?: T;
        mono?: T;
      };
  fontSize?:
    | T
    | {
        base?: T;
        scale?: T;
      };
  spacing?:
    | T
    | {
        unit?: T;
        containerMaxWidth?: T;
        contentMaxWidth?: T;
      };
  borderRadius?:
    | T
    | {
        sm?: T;
        md?: T;
        lg?: T;
      };
  shadow?:
    | T
    | {
        sm?: T;
        md?: T;
        lg?: T;
      };
  customCSS?: T;
  status?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions_select".
 */
export interface PermissionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  resource?: T;
  action?: T;
  description?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  level?: T;
  parentRole?: T;
  permissions?: T;
  inheritedPermissions?: T;
  status?: T;
  isSystemRole?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  siteName: string;
  siteDescription?: string | null;
  logo?: (string | null) | Media;
  favicon?: (string | null) | Media;
  contactEmail?: string | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'twitter' | 'instagram' | 'linkedin' | 'youtube' | 'github';
        url: string;
        id?: string | null;
      }[]
    | null;
  tableSettings?: {
    defaultPageSize?: ('5' | '10' | '20' | '50' | '100') | null;
    /**
     * Comma-separated values (e.g., 5,10,20,50,100)
     */
    pageSizeOptions?: string | null;
    /**
     * Show status tabs above the table by default
     */
    showStatusTabs?: boolean | null;
    /**
     * Show filter controls in the toolbar
     */
    showFilters?: boolean | null;
    /**
     * Show global search input
     */
    showSearch?: boolean | null;
    /**
     * Allow users to toggle column visibility
     */
    showColumnVisibility?: boolean | null;
    /**
     * Sync table state with browser URL
     */
    enableUrlSync?: boolean | null;
    dateFormat?: ('PP' | 'PPP' | 'PPPP' | 'yyyy-MM-dd' | 'dd/MM/yyyy' | 'MM/dd/yyyy') | null;
    dateTimeFormat?: ('PPp' | 'PPPp' | "yyyy-MM-dd'T'HH:mm:ss" | 'dd/MM/yyyy HH:mm' | 'MM/dd/yyyy hh:mm a') | null;
  };
  themeSettings?: {
    defaultTheme?: ('light' | 'dark' | 'system') | null;
    /**
     * Primary brand color (hex format)
     */
    primaryColor?: string | null;
    /**
     * Accent color for highlights (hex format)
     */
    accentColor?: string | null;
  };
  apiSettings?: {
    /**
     * Allow public access to API endpoints
     */
    enableApi?: boolean | null;
    rateLimitRequests?: number | null;
    enableCors?: boolean | null;
    allowedOrigins?:
      | {
          origin: string;
          id?: string | null;
        }[]
      | null;
  };
  emailSettings?: {
    fromName?: string | null;
    fromEmail?: string | null;
    replyToEmail?: string | null;
    /**
     * Footer content for all outgoing emails
     */
    emailFooter?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  logo?: T;
  favicon?: T;
  contactEmail?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  tableSettings?:
    | T
    | {
        defaultPageSize?: T;
        pageSizeOptions?: T;
        showStatusTabs?: T;
        showFilters?: T;
        showSearch?: T;
        showColumnVisibility?: T;
        enableUrlSync?: T;
        dateFormat?: T;
        dateTimeFormat?: T;
      };
  themeSettings?:
    | T
    | {
        defaultTheme?: T;
        primaryColor?: T;
        accentColor?: T;
      };
  apiSettings?:
    | T
    | {
        enableApi?: T;
        rateLimitRequests?: T;
        enableCors?: T;
        allowedOrigins?:
          | T
          | {
              origin?: T;
              id?: T;
            };
      };
  emailSettings?:
    | T
    | {
        fromName?: T;
        fromEmail?: T;
        replyToEmail?: T;
        emailFooter?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}